version: '3.4'

services:
  api:
    image: addcode-practicum:video-chat-api
    container_name: video-chat-api
    restart: always
    ports:
      - 5000:5000

  nginx:
    image: addcode-practicum:video-chat-proxy
    container_name: video-chat-proxy
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 4000:4000
    depends_on:
      - api
